# Generated by Django 4.2.3 on 2025-12-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_class_member_membershiptype_membershiphistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='contact',
            field=models.CharField(blank=True, help_text='Номер телефону', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='specialties',
            field=models.TextField(default='General'),
            preserve_default=False,
        ),
    ]
