# Generated by Django 4.2.3 on 2026-02-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_instructor_contact_alter_instructor_specialties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наприклад: Зал Йоги, Басейн', max_length=100)),
                ('capacity', models.IntegerField(default=20, help_text='Максимальна місткість залу')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Записано'), ('attended', 'Відвідав'), ('missed', 'Пропустив'), ('cancelled', 'Скасовано')], default='booked', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Готівка'), ('card', 'Картка (Термінал)'), ('online', 'Онлайн оплата')], default='cash', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'В обробці'), ('completed', 'Успішно'), ('failed', 'Помилка')], default='completed', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.member')),
                ('membership_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.membershiphistory')),
            ],
        ),
        migrations.AddField(
            model_name='classsession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.room'),
        ),
    ]
