# Generated by Django 4.2.3 on 2026-03-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_room_alter_booking_status_payment_classsession_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ім'я клієнта", max_length=100)),
                ('phone', models.CharField(help_text='Контактний телефон', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В роботі'), ('completed', 'Успішно продано'), ('cancelled', 'Відмова')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership_type', models.ForeignKey(blank=True, help_text='Бажаний тариф', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.membershiptype')),
            ],
            options={
                'verbose_name': 'Заявка на абонемент',
                'verbose_name_plural': 'Заявки на абонементи',
                'ordering': ['-created_at'],
            },
        ),
    ]
