# Generated by Django 4.2.3 on 2026-04-23 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_membershipapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gym_logos/')),
                ('owner_contact', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='Europe/Kyiv', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='time_limit_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='time_limit_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_access_granted', models.BooleanField()),
                ('denial_reason', models.CharField(blank=True, max_length=255)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='crm.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='crm.member')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='crm.gym'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='crm.gym'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='crm.gym'),
        ),
        migrations.AddField(
            model_name='member',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crm.gym'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='crm.gym'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_types', to='crm.gym'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.gym'),
        ),
    ]
