# Generated by Django 4.2.3 on 2026-05-14 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_gym_membershiptype_time_limit_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, default=0)),
                ('telegram_username', models.CharField(blank=True, max_length=64)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('link_code', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('link_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to='crm.member')),
            ],
        ),
    ]
