# Generated by Django 4.2.3 on 2026-05-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_telegramlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='deposit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kind', models.CharField(choices=[('topup', 'Поповнення'), ('charge', 'Списання'), ('refund', 'Повернення'), ('adjust', 'Коригування адміном')], max_length=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='crm.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='crm.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
